### ISSUE TITLE
add in a system to enforce namespace consensus

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#1]

**Comment by jcnelson** [comment]
Building the consensus hash over the *entire* namespace for each block has proven very costly, even for a small number of users (in the 10,000 range).  I am currently using a consensus hash generation algorithm that simply builds a Merkle tree over the name operations discovered in the current block, and includes the consensus hash of the previous block as one of the hashes.  This not only lets two Blockstore peers prove that they have processed the same operations, but also that they have processed them in the same order.  This is applied by [virtualchain](https://github.com/blockstack/virtualchain), since virtualchain allows there to be arbitrary side-effects, whose final states are dependent on the order in which operations are processed.

As discussed elsewhere, non-idempotent operations (i.e. ones that conflict) that can be issued by more than one principal need to include the Merkle hash to guarantee at-most-once semantics.  This would include preordering, updating, transferring, and namepace preordering.  

Users shouldn't need to announce their Merkle roots; only their names (and only once the name has been *registered*).  Once the name has been registered, Blockstore peers will have had to have processed the preorder, and will have had to agree on the same Merkle root at the time of the preorder.

All of this has been implemented, so I'm going to close this issue.  Please re-open if we need to revisit the consensus hash algorithm.

**Comment by shea256** [comment]
Sounds good. We should open a new thread at some point around just SPV support.

**Comment by brandonrobertz** [comment]
Namecoin sounds a lot easier at this point IMO.

**Comment by muneeb-ali** [comment]
SPV support has been added in Blockstore. Namecoin has its advantages and disadvantages, we summarized lessons from our year long deployment on Namecoin [here](http://blog.onename.com/namecoin-to-bitcoin/).

**Comment by muneeb-ali** [comment]
To be clear, the SPV-like support has been added in the [develop branch](https://github.com/blockstack/blockstore/tree/develop) and is not fully available on the last stable release. The code is there, but we're in the process of releasing the documentation. This implements a new Merkle skip-lists based solution. The documentation will be published [here](https://github.com/blockstack/blockstore/wiki), when it's ready. Stay tuned.
