### ISSUE TITLE
lay out the steps remaining/design tradeoffs for the simplest first release

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#38]
Thinking through the ways that we can ship a working, simple first release (our "pre-pre-ultra-test-alpha-RFC"). This should involve making things as simple as possible.

Some points of discussion:

1. Should salt be removed from preorders and registrations? See #37
2. Is the consensus hash absolutely necessary? Should it be kept in the first release? (It significantly complicates things). Perhaps we should get some outside guidance on the necessary properties for us to maintain a stable consensus.
3. Should the namespace-specific pricing policy be incorporated in? Or should it be simple in the first release, with the opportunity to open a discussion before its implemented? See #20
4. Should we ship the first release with a non-miner-attackable name price payment scheme? If so, then we could make a super simple fix by switching from mining fee to burn. The other option is go take the time to implement one of the miner-attack-resistant methods we discussed, but that'll be a larger project. See #25
5. How many nodes and DHTs should we have up online?

**Comment by jcnelson** [comment]
Wrapping this up from months of design discussions:

1. No.  Any preorder must be salted; otherwise a squatter could brute-force the hash with a dictionary attack.
2. It should be necessary for preorders, updates, transfers, and namespace preorders--operations that need to prove that the issuer had the latest state of the namespace (since these operations can conflict with one another).
3. Yes; this is implemented.
4. Yes; we burn the fees.
5. Have application servers (including ours) run DHT nodes.  Don't have the clients run them; otherwise there will be too much churn.

**Comment by shea256** [comment]
:+1:
