### ISSUE TITLE
How to get consensus hash ?

### ISSUE THREAD

**Issue by cqtenq** [blockstack/blockstore#87]
consensus hash= calculate_merkle_snapshot(db) ?

**Comment by jcnelson** [comment]
This is the last 16 bytes of the Merkle tree calculated over the previous consensus hash and the current block's extracted name operations.  It represents the state of the virtual chain at the given block.

This functionality has since migrated to [virtualchain](https://github.com/blockstack/virtualchain).  I'm going to close this issue here.  If you have any further questions on how virtualchain works, please open issues in its issue tracker.  Thanks!
